M48
; DRILL file {KiCad 9.0.1} date 2025-04-14T23:47:01-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-14T23:47:01-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.048
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X46.967Y-126.562
T2
X24.0Y-84.0
X24.0Y-126.0
X140.0Y-84.0
X140.0Y-126.0
X256.0Y-84.0
X256.0Y-126.0
M30
